protected/admin/controllers/ProcategoryController.php
<?php

class ProcategoryController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
                                'users'=>array('@'),
                                'expression'=>'CFunc::checkRight(CR_PROCATEGORY)',
                        ),
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('create'),
                                'users'=>array('@'),
                                'expression'=>'CFunc::checkRight(CR_PROCATEGORY)',
                        ),
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('update'),
                                'users'=>array('@'),
                                'expression'=>'CFunc::checkRight(CR_PROCATEGORY)',
                        ),
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('delete'),
                                'users'=>array('@'),
                                'expression'=>'CFunc::checkRight(CR_PROCATEGORY)',
                        ),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Procategory;
                
                //设置默认值
                $model->weight=50;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Procategory']))
		{
			$model->attributes=$_POST['Procategory'];
			if($model->save()){
                            //ajax提交的，保存成功
                            echo '{
                                    "statusCode":"200",
                                    "message":"分类已添加",
                                    "navTabId":"",
                                    "rel":"",
                                    "callbackType":"closeCurrentAndJump",
                                    "jumpId":"procategory",
                                    "jumpUrl":"'.$this->createUrl('procategory/index').'",
                                    "jumpTitle":"分类列表",
                                    "forwardUrl":"",
                                    "confirmMsg":""
                            }';
                            Yii::app()->end();
                        }
                        else{
                            //ajax提交的，保存不成功
                            $tempFlash="请与管理员联系。";
                            if(Yii::app()->user->hasFlash('saveError'))
                                    $tempFlash=Yii::app()->user->getFlash('saveError');
                            echo '{
                                    "statusCode":"300",
                                    "message":"分类添加不成功。'.$tempFlash.'",
                                    "navTabId":"",
                                    "rel":"",
                                    "callbackType":"",
                                    "forwardUrl":"",
                                    "confirmMsg":""
                            }';
                            Yii::app()->end();
                        }
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Procategory']))
		{
			$model->attributes=$_POST['Procategory'];
			if($model->save()){
                            //ajax提交的，保存成功
                            echo '{
                                    "statusCode":"200",
                                    "message":"修改已保存",
                                    "navTabId":"",
                                    "rel":"",
                                    "callbackType":"closeCurrentAndJump",
                                    "jumpId":"procategory",
                                    "jumpUrl":"'.$this->createUrl('procategory/index').'",
                                    "jumpTitle":"分类列表",
                                    "forwardUrl":"",
                                    "confirmMsg":""
                            }';
                            Yii::app()->end();
                        }
                        else{
                            //ajax提交的，保存不成功
                            $tempFlash="请与管理员联系。";
                            if(Yii::app()->user->hasFlash('saveError'))
                                    $tempFlash=Yii::app()->user->getFlash('saveError');
                            echo '{
                                    "statusCode":"300",
                                    "message":"修改不成功。'.$tempFlash.'",
                                    "navTabId":"",
                                    "rel":"",
                                    "callbackType":"",
                                    "forwardUrl":"",
                                    "confirmMsg":""
                            }';
                            Yii::app()->end();
                        }
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();
                        
                        //删除成功
                        echo '{
                                "statusCode":"200",
                                "message":"删除成功",
                                "navTabId":"procategory",
                                "rel":"",
                                "callbackType":"",
                                "forwardUrl":"",
                                "confirmMsg":""
                        }';
                        Yii::app()->end();
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$this->render('index');
	}

	/**
	 * Manages all models.
	public function actionAdmin()
	{
		$model=new Procategory('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Procategory']))
			$model->attributes=$_GET['Procategory'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}
	 */

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Procategory::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='procategory-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/admin/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	public $layout='//layouts/main';
        
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}
        
	public function accessRules()
	{
		return array(
			array(
                            'allow',
                            'actions'=>array('index','logout','viewimg','flushcache'),
                            'users'=>array('@'),
			),
			array(
                            'allow',
                            'actions'=>array('login','ajaxlogin','error'),
                            'users'=>array('*'),
			),
			array(
                            'deny',  // deny all users
                            'users'=>array('*'),
			),
		);
	}
        
	public function actionIndex()
	{
		$this->render('index');
	}
        
	public function actionViewimg($imgsrc)
	{
                echo CHtml::image(CFunc::srcUrlDecode($imgsrc));
	}
        
	public function actionError()
	{
	    if($error=Yii::app()->errorHandler->error)
	    {
	    	if(Yii::app()->request->isAjaxRequest){
	    		echo $error['message'];
		}
	    	else{
                    $this->render('error', $error);
		}
	    }
	}
        
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login()){
                                CFunc::writeLog('登陆系统');
				$this->redirect(array("index"));
                        }
		}
		// display the login form

                $this->pageTitle=Yii::app()->name.' - 登陆';
		$this->render('login',array('model'=>$model));
	}
        
	public function actionAjaxlogin()
	{
		$model=new LoginForm;

		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login()){
                                CFunc::writeLog('重新登陆系统');
				echo '{"statusCode":"200", "message":"重新登陆成功！", "callbackType":"closeCurrent"}';
                                Yii::app()->end();
                        }
			else{
                                echo '{"statusCode":"300", "message":"用户名或密码错误，登陆不成功！"}';
                                Yii::app()->end();
                        }
		}
                
		$this->render('ajaxlogin');
	}
        
	public function actionLogout()
	{
                CFunc::writeLog('退出系统');
		Yii::app()->user->logout();
		$this->redirect("/");
	}
        
        /*
         * 清理后台的缓存
         */
        public function actionFlushcache(){
                CFunc::flushCache(true);
        }
}

protected/admin/controllers/UploadController.php
<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of Upload
 *
 * @author Uploadistrator
 */
class UploadController extends Controller {
    //put your code here
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow upload user to perform 'upload' and 'delete' actions
				'actions'=>array('link','image','flash','media','attachment'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
        
        /*
         * 附件上传，纯上传，不生成缩略图
         */
        public function actionLink(){
            try{
                //$_FILES["Filedata"]["size"];
                $retval="";
                $pt=strrpos($_FILES["Filedata"]["name"], ".");
                if($pt) $retval=substr($_FILES["Filedata"]["name"], $pt);
                else $retval=".linktmp";
                //$tempArr=explode('.',$_FILES["Filedata"]["name"]);
                $fileName = md5(rand()*10000000);
                $fileName = UPLOADLINK_PATH.'/' . $fileName;
                $fileName = $fileName . $retval;
                move_uploaded_file($_FILES["Filedata"]["tmp_name"], $fileName);

                echo '{"err":"","msg":"'.Yii::app()->baseUrl.'/'.$fileName.'"}';
            } catch (Exception $exc) {
                echo '{"err":"1","msg":"上传失败，请与管理员联系"}';
            }
        }
        
        /*
         * 图片上传，纯上传，不生成缩略图
         */
        public function actionImage(){
            try{
                $retval="";
                $pt=strrpos($_FILES["Filedata"]["name"], ".");
                if($pt) $retval=substr($_FILES["Filedata"]["name"], $pt);
                else $retval=".imagetmp";
                //$tempArr=explode('.',$_FILES["Filedata"]["name"]);
                $fileName = md5(rand()*10000000);
                $fileName = UPLOADIMAGE_PATH.'/' . $fileName;
                $fileName = $fileName . $retval;
                @move_uploaded_file($_FILES["Filedata"]["tmp_name"], $fileName);
                
                //通过image扩展自动生成缩小图
                $smallFileName=CFunc::getSmallImg($fileName,true);
                //用下边的图片另存
                //@copy($fileName,$smallFileName);
                
                //以下采用Yii设入image扩展包进行缩放处理
                $image = Yii::app()->image->load($fileName);
                $image->resize(SMALLPIC_SIZE_WIDTH, SMALLPIC_SIZE_HEIGHT);//自动保持比例，设定为宽最大值和高最大值
                //$image->resize(400, 100)->rotate(-45)->quality(75)->sharpen(20);
                $image->save($smallFileName); // or $image->save('images/small.jpg');

                echo '{"err":"","msg":"'.Yii::app()->baseUrl.'/'.$fileName.'"}';
            } catch (Exception $exc) {
                echo '{"err":"1","msg":"上传失败，请与管理员联系"}';
            }
        }
        
        /*
         * FLASH上传，纯上传，不生成缩略图
         */
        public function actionFlash(){
            try{
                $retval="";
                $pt=strrpos($_FILES["Filedata"]["name"], ".");
                if($pt) $retval=substr($_FILES["Filedata"]["name"], $pt);
                else $retval=".flashtmp";
                //$tempArr=explode('.',$_FILES["Filedata"]["name"]);
                $fileName = md5(rand()*10000000);
                $fileName = UPLOADFLASH_PATH.'/' . $fileName;
                $fileName = $fileName . $retval;
                @move_uploaded_file($_FILES["Filedata"]["tmp_name"], $fileName);

                echo '{"err":"","msg":"'.Yii::app()->baseUrl.'/'.$fileName.'"}';
            } catch (Exception $exc) {
                echo '{"err":"1","msg":"上传失败，请与管理员联系"}';
            }
        }
        
        /*
         * 媒体上传，纯上传，不生成缩略图
         */
        public function actionMedia(){
            try{
                $retval="";
                $pt=strrpos($_FILES["Filedata"]["name"], ".");
                if($pt) $retval=substr($_FILES["Filedata"]["name"], $pt);
                else $retval=".mediatmp";
                //$tempArr=explode('.',$_FILES["Filedata"]["name"]);
                $fileName = md5(rand()*10000000);
                $fileName = UPLOADMEDIA_PATH.'/' . $fileName;
                $fileName = $fileName . $retval;
                @move_uploaded_file($_FILES["Filedata"]["tmp_name"], $fileName);

                echo '{"err":"","msg":"'.Yii::app()->baseUrl.'/'.$fileName.'"}';
            } catch (Exception $exc) {
                echo '{"err":"1","msg":"上传失败，请与管理员联系"}';
            }
        }
        
        /*
         * 附件上传，返回原文件名不生成缩略图
         */
        public function actionAttachment(){
            try{
                $retval="";
                $pt=strrpos($_FILES["Filedata"]["name"], ".");
                if($pt) $retval=substr($_FILES["Filedata"]["name"], $pt);
                else $retval=".attachmenttmp";
                //$tempArr=explode('.',$_FILES["Filedata"]["name"]);
                $fileName = md5(rand()*10000000);
                $fileName = UPLOADATTACHMENT_PATH.'/' . $fileName;
                $fileName = $fileName . $retval;
                @move_uploaded_file($_FILES["Filedata"]["tmp_name"], $fileName);

                echo '{"err":"","msg":"'.$_FILES["Filedata"]["name"].'|&|'.Yii::app()->baseUrl.'/'.$fileName.'"}';
            } catch (Exception $exc) {
                echo '{"err":"1","msg":"上传失败，请与管理员联系"}';
            }
        }
}

?>

protected/admin/views/procategory/create.php
<?php Yii::app()->clientScript->scriptMap = array('jquery.js'=>false, 'jquery.min.js'=>false);?>
<div class="pageContent">
	<div class="panelBar">
		<ul class="toolBar">
		</ul>
	</div>
        <?php
        /*
         * 提供父栏目选项，先行整理栏目树形结构
         */
        $procategoryArr=CFunc::getProSonTree();

        //把树形用缩进显示出来
        $procategoryIds['0']='根目录';
        foreach($procategoryArr as $procategoryItem){
            $procategoryIds[$procategoryItem['category']->id]=CFunc::repeatStr('┈┈',$procategoryItem['generation']-1).$procategoryItem['category']->categoryname;
        }

        /*
         * 提供模板选项
         */
        $protemplateArr=Protemplate::model()->findAll(array('order'=>'id desc'));
        $protemplateIds=array();
        $protemplateIds['0']='默认模板';
        foreach ($protemplateArr as $protemplateItem){
            $protemplateIds[$protemplateItem->id]=$protemplateItem->title;
        };

        ?>
        <?php $form=$this->beginWidget('ext.dwz.DwzActiveForm', array(
                'id'=>'procategory_create-form',
                'enableAjaxValidation'=>false,
                'htmlOptions'=>array(
                    'class'=>'pageForm required-validate',
                    'onsubmit'=>'return validateCallback(this, navTabAjaxDone);',
                ),
        )); ?>

                        <div class="pageFormContent nowrap" layoutH="83">
                                <dl>
                                        <dt><?php echo $form->label($model,'parent_id'); ?></dt>
                                        <dd><?php echo $form->dropDownList($model,'parent_id',$procategoryIds); ?></dd>
                                </dl>
                                <dl>
                                        <dt><?php echo $form->label($model,'categoryname'); ?></dt>
                                        <dd><?php echo $form->textField($model,'categoryname',array('size'=>30,'maxlength'=>100)); ?></dd>
                                </dl>
                                <dl>
                                        <dt><?php echo $form->label($model,'weight'); ?></dt>
                                        <dd><?php echo $form->textField($model,'weight',array('size'=>30,'maxlength'=>100)); ?></dd>
                                </dl>
                                <dl>
                                        <dt><?php echo $form->label($model,'image'); ?></dt>
                                        <dd><?php echo $form->textField($model,'image',array(
                                            'id'=>'create_procategory_image',
                                            'size'=>30,
                                            'maxlength'=>100,
                                            'class'=>'forswfupload',
                                            'flash_url'=>"/inc/swfupload/swfupload.swf",
                                            'flash9_url'=>"/inc/swfupload/swfupload_fp9.swf",
                                            'upload_url'=>$this->createUrl('upload/image'),
                                            'post_params'=>'{"PHPSESSID" : "'.session_id().'"}',
                                            'file_size_limit'=>"3 MB",
                                            'file_types'=>"*.jpg;*.gif;*.png;*.jpeg",
                                            'file_types_description'=>"图片",
                                            'custom_settings'=>'{
                                                    progressTarget : "create_procategory_fsUploadProgress",
                                                    imageField : "create_procategory_image",
                                                    imageViewField : "create_procategory_image_preview"
                                            }',
                                            'button_placeholder_id'=>"create_procategory_upload_holder",
                                            //'debug'=>'false',

                                            // Button settings
                                            //'button_image_url'=>"/images/SmallSpyGlassWithTransperancy_17x18.png",
                                            //'button_width'=>"140",
                                            //'button_height'=>"18",
                                            'button_text'=>'<span class="sud_btn">本地上传 <span class="sud_sbtn">(3 MB max)</span></span>',
                                            //'button_text_style'=>'.sud_btn { font-family: Helvetica, Arial, sans-serif; font-size: 12pt; } .sud_sbtn { font-size: 10pt; }',
                                            //'button_text_top_padding'=>'0',
                                            //'button_text_left_padding'=>'18',
                                            'upload_success_handler'=>'uploadSuccessForImage',
                                        )); ?>
                                        <div class="swfuploadbtn"><span id="create_procategory_upload_holder"></span></div>
                                        <div class="fieldset flash" id="create_procategory_fsUploadProgress"></div>
                                        </dd>
                                </dl>
                                <dl id="create_procategory_image_preview">
                                        <?php if(!empty($model->image)) echo '<dt><label>图片预览</label></dt><dd>'.CHtml::link(CHtml::image(CFunc::getSmallImg($model->image),null,array('border'=>'0')),array('site/viewimg','imgsrc'=>CFunc::srcUrlEncode($model->image)),array('target'=>'dialog','title'=>'查看原图')).'</dd>'; ?>
                                </dl>
                                <dl>
                                        <dt><?php echo $form->label($model,'protemplate_id'); ?></dt>
                                        <dd><?php echo $form->dropDownList($model,'protemplate_id',$protemplateIds); ?></dd>
                                </dl>
                                <dl>
                                        <dt><?php echo $form->label($model,'introduction'); ?></dt>
                                        <dd><?php echo $form->textArea($model,'introduction',array(
                                            'rows'=>15,
                                            'cols'=>107,
                                            'class'=>'editor',
                                            'upLinkUrl'=>$this->createUrl('upload/link'),
                                            'upLinkExt'=>"zip,rar,txt",
                                            'upImgUrl'=>$this->createUrl('upload/image'),
                                            'upImgExt'=>"jpg,jpeg,gif,png",
                                            'upFlashUrl'=>$this->createUrl('upload/flash'),
                                            'upFlashExt'=>"swf",
                                            'upMediaUrl'=>$this->createUrl('upload/media'),
                                            'upMediaExt'=>"avi,flv,mp4,mp3",
                                            "id"=>"create_procategory_introduction"
                                            )); ?></dd>
                                </dl>
                        </div>
                        <div class="formBar">
                                <ul>
                                        <!--<li><a class="buttonActive" href="javascript:;"><span>保存</span></a></li>-->
                                        <li><div class="buttonActive"><div class="buttonContent"><button type="submit">保存</button></div></div></li>
                                        <li>
                                                <div class="button"><div class="buttonContent"><button type="button" class="close">取消</button></div></div>
                                        </li>
                                </ul>
                        </div>

        <?php $this->endWidget(); ?>
</div>

protected/admin/views/procategory/index.php
<?php Yii::app()->clientScript->scriptMap = array('jquery.js'=>false, 'jquery.min.js'=>false);?>
<div class="pageContent">
	<div class="panelBar">
		<ul class="toolBar">
			<li><a class="add" href="<?php echo $this->createUrl('create');?>" target="navTab" title="添加分类" rel="createProcategory"><span>添加</span></a></li>
			<li><a class="delete" href="<?php echo $this->createUrl('delete',array('id'=>'{procategory_id}'));?>" target="ajaxTodo" title="确定要删除吗?"><span>删除</span></a></li>
			<li><a class="edit" href="<?php echo $this->createUrl('update',array('id'=>'{procategory_id}'));?>" target="navTab" title="修改分类" rel="updateProcategory"><span>修改</span></a></li>
			<li><a class="view" href="<?php echo $this->createUrl('view',array('id'=>'{procategory_id}'));?>" target="navTab" title="分类详情" rel="viewProcategory"><span>详情</span></a></li>
		</ul>
	</div>
        <table class="list" width="100%" layoutH="47">
            <thead>
                <tr>
                    <th align="center">分类名称</th>
                    <th width="80" align="center">排序权重</th>
                    <th width="200" align="center">采用模板</th>
                </tr>
            </thead>
            <tbody>
        <?php
        $procategoryArr=CFunc::getProSonTree();
        foreach ($procategoryArr as $procategoryItem){
            echo '<tr target="procategory_id" rel="'.$procategoryItem['category']->id.'">';
            echo '<td align="left">'.CFunc::repeatStr('　　',$procategoryItem['generation']-1).' '.$procategoryItem['category']->categoryname.'</td>';
            echo '<td align="center">'.$procategoryItem['category']->weight.'</td>';
            if(isset($procategoryItem['category']->protemplate->title))
                $templateTitle=$procategoryItem['category']->protemplate->title;
            else
                $templateTitle="默认模板";
            echo '<td align="center">'.$templateTitle.'</td>';
            echo '</tr>';
        }
        ?>
            </tbody>
        </table>
</div>

protected/admin/views/procategory/view.php
<?php Yii::app()->clientScript->scriptMap = array('jquery.js'=>false, 'jquery.min.js'=>false);?>
<div class="pageContent">
	<div class="panelBar">
		<ul class="toolBar">
			<li><a class="add" href="<?php echo $this->createUrl('create');?>" target="navTab" title="添加分类" rel="createProcategory"><span>添加</span></a></li>
			<li><a class="edit" href="<?php echo $this->createUrl('update',array('id'=>$model->id));?>" target="navTab" title="修改分类" rel="updateProcategory"><span>修改</span></a></li>
		</ul>
	</div>
        <div class="pageFormContent nowrap" layoutH="47">
                <dl>
                    <dt><?php echo CHtml::activeLabel($model, 'id'); ?></dt>
                    <dd><?php echo $model->id; ?></dd>
                </dl>
		<div class="divider"></div>
                <dl>
                    <dt><?php echo CHtml::activeLabel($model, 'weight'); ?></dt>
                    <dd><?php echo $model->weight; ?></dd>
                </dl>
		<div class="divider"></div>
                <dl>
                    <dt><label>父栏目</label></dt>
                    <dd><?php echo $model->getParents($model->parent_id); ?></dd>
                </dl>
		<div class="divider"></div>
                <dl>
                    <dt><?php echo CHtml::activeLabel($model, 'categoryname'); ?></dt>
                    <dd><?php echo $model->categoryname; ?></dd>
                </dl>
		<div class="divider"></div>
                <dl>
                    <dt><?php echo CHtml::activeLabel($model, 'image'); ?></dt>
                    <dd><?php echo $model->image==''?'无图':CHtml::link(CHtml::image(CFunc::getSmallImg($model->image),null,array('border'=>'0')),array('site/viewimg','imgsrc'=>CFunc::srcUrlEncode($model->image)),array('target'=>'dialog','title'=>'查看原图')); ?></dd>
                </dl>
		<div class="divider"></div>
                <dl>
                    <dt><?php echo CHtml::activeLabel($model, 'protemplate_id'); ?></dt>
                    <dd><?php echo $model->protemplate_id==0?'默认模板':$model->protemplate->title; ?></dd>
                </dl>
		<div class="divider"></div>
                <dl>
                    <dt><?php echo CHtml::activeLabel($model, 'introduction'); ?></dt>
                    <dd><?php echo $model->introduction; ?></dd>
                </dl>
        </div>
</div>